INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00001', 'PAN00001', 'CMP001', 'DPSU1', N'Company_001', 'contact@company_001.com', '1234567890', 'info@company_001.com', 'Address 1', 'City1', '100001', 2, 'District1', 'State1', 'https://company_001.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC1', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00002', 'PAN00002', 'CMP002', 'DPSU2', N'Company_002', 'contact@company_002.com', '1234567890', 'info@company_002.com', 'Address 2', 'City2', '100002', 3, 'District2', 'State2', 'https://company_002.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC2', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00003', 'PAN00003', 'CMP003', 'DPSU3', N'Company_003', 'contact@company_003.com', '1234567890', 'info@company_003.com', 'Address 3', 'City3', '100003', 4, 'District3', 'State3', 'https://company_003.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC3', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00004', 'PAN00004', 'CMP004', 'DPSU4', N'Company_004', 'contact@company_004.com', '1234567890', 'info@company_004.com', 'Address 4', 'City4', '100004', 1, 'District4', 'State4', 'https://company_004.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC4', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00005', 'PAN00005', 'CMP005', 'DPSU5', N'Company_005', 'contact@company_005.com', '1234567890', 'info@company_005.com', 'Address 5', 'City5', '100005', 2, 'District5', 'State5', 'https://company_005.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC5', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00006', 'PAN00006', 'CMP006', 'DPSU6', N'Company_006', 'contact@company_006.com', '1234567890', 'info@company_006.com', 'Address 6', 'City6', '100006', 3, 'District6', 'State6', 'https://company_006.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC6', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00007', 'PAN00007', 'CMP007', 'DPSU7', N'Company_007', 'contact@company_007.com', '1234567890', 'info@company_007.com', 'Address 7', 'City7', '100007', 4, 'District7', 'State7', 'https://company_007.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC7', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00008', 'PAN00008', 'CMP008', 'DPSU8', N'Company_008', 'contact@company_008.com', '1234567890', 'info@company_008.com', 'Address 8', 'City8', '100008', 1, 'District8', 'State8', 'https://company_008.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC8', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00009', 'PAN00009', 'CMP009', 'DPSU9', N'Company_009', 'contact@company_009.com', '1234567890', 'info@company_009.com', 'Address 9', 'City9', '100009', 2, 'District9', 'State9', 'https://company_009.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC9', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00010', 'PAN00010', 'CMP010', 'DPSU10', N'Company_010', 'contact@company_010.com', '1234567890', 'info@company_010.com', 'Address 10', 'City10', '1000010', 3, 'District10', 'State10', 'https://company_010.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC10', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00011', 'PAN00011', 'CMP011', 'DPSU11', N'Company_011', 'contact@company_011.com', '1234567890', 'info@company_011.com', 'Address 11', 'City11', '1000011', 4, 'District11', 'State11', 'https://company_011.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC11', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00012', 'PAN00012', 'CMP012', 'DPSU12', N'Company_012', 'contact@company_012.com', '1234567890', 'info@company_012.com', 'Address 12', 'City12', '1000012', 1, 'District12', 'State12', 'https://company_012.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC12', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00013', 'PAN00013', 'CMP013', 'DPSU13', N'Company_013', 'contact@company_013.com', '1234567890', 'info@company_013.com', 'Address 13', 'City13', '1000013', 2, 'District13', 'State13', 'https://company_013.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC13', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00014', 'PAN00014', 'CMP014', 'DPSU14', N'Company_014', 'contact@company_014.com', '1234567890', 'info@company_014.com', 'Address 14', 'City14', '1000014', 3, 'District14', 'State14', 'https://company_014.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC14', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00015', 'PAN00015', 'CMP015', 'DPSU15', N'Company_015', 'contact@company_015.com', '1234567890', 'info@company_015.com', 'Address 15', 'City15', '1000015', 4, 'District15', 'State15', 'https://company_015.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC15', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00016', 'PAN00016', 'CMP016', 'DPSU16', N'Company_016', 'contact@company_016.com', '1234567890', 'info@company_016.com', 'Address 16', 'City16', '1000016', 1, 'District16', 'State16', 'https://company_016.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC16', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00017', 'PAN00017', 'CMP017', 'DPSU17', N'Company_017', 'contact@company_017.com', '1234567890', 'info@company_017.com', 'Address 17', 'City17', '1000017', 2, 'District17', 'State17', 'https://company_017.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC17', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00018', 'PAN00018', 'CMP018', 'DPSU18', N'Company_018', 'contact@company_018.com', '1234567890', 'info@company_018.com', 'Address 18', 'City18', '1000018', 3, 'District18', 'State18', 'https://company_018.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC18', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00019', 'PAN00019', 'CMP019', 'DPSU19', N'Company_019', 'contact@company_019.com', '1234567890', 'info@company_019.com', 'Address 19', 'City19', '1000019', 4, 'District19', 'State19', 'https://company_019.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC19', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00020', 'PAN00020', 'CMP020', 'DPSU20', N'Company_020', 'contact@company_020.com', '1234567890', 'info@company_020.com', 'Address 20', 'City20', '1000020', 1, 'District20', 'State20', 'https://company_020.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC20', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00021', 'PAN00021', 'CMP021', 'DPSU21', N'Company_021', 'contact@company_021.com', '1234567890', 'info@company_021.com', 'Address 21', 'City21', '1000021', 2, 'District21', 'State21', 'https://company_021.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC21', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00022', 'PAN00022', 'CMP022', 'DPSU22', N'Company_022', 'contact@company_022.com', '1234567890', 'info@company_022.com', 'Address 22', 'City22', '1000022', 3, 'District22', 'State22', 'https://company_022.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC22', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00023', 'PAN00023', 'CMP023', 'DPSU23', N'Company_023', 'contact@company_023.com', '1234567890', 'info@company_023.com', 'Address 23', 'City23', '1000023', 4, 'District23', 'State23', 'https://company_023.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC23', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00024', 'PAN00024', 'CMP024', 'DPSU24', N'Company_024', 'contact@company_024.com', '1234567890', 'info@company_024.com', 'Address 24', 'City24', '1000024', 1, 'District24', 'State24', 'https://company_024.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC24', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00025', 'PAN00025', 'CMP025', 'DPSU25', N'Company_025', 'contact@company_025.com', '1234567890', 'info@company_025.com', 'Address 25', 'City25', '1000025', 2, 'District25', 'State25', 'https://company_025.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC25', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00026', 'PAN00026', 'CMP026', 'DPSU26', N'Company_026', 'contact@company_026.com', '1234567890', 'info@company_026.com', 'Address 26', 'City26', '1000026', 3, 'District26', 'State26', 'https://company_026.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC26', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00027', 'PAN00027', 'CMP027', 'DPSU27', N'Company_027', 'contact@company_027.com', '1234567890', 'info@company_027.com', 'Address 27', 'City27', '1000027', 4, 'District27', 'State27', 'https://company_027.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC27', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00028', 'PAN00028', 'CMP028', 'DPSU28', N'Company_028', 'contact@company_028.com', '1234567890', 'info@company_028.com', 'Address 28', 'City28', '1000028', 1, 'District28', 'State28', 'https://company_028.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC28', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00029', 'PAN00029', 'CMP029', 'DPSU29', N'Company_029', 'contact@company_029.com', '1234567890', 'info@company_029.com', 'Address 29', 'City29', '1000029', 2, 'District29', 'State29', 'https://company_029.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC29', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00030', 'PAN00030', 'CMP030', 'DPSU30', N'Company_030', 'contact@company_030.com', '1234567890', 'info@company_030.com', 'Address 30', 'City30', '1000030', 3, 'District30', 'State30', 'https://company_030.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC30', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00031', 'PAN00031', 'CMP031', 'DPSU31', N'Company_031', 'contact@company_031.com', '1234567890', 'info@company_031.com', 'Address 31', 'City31', '1000031', 4, 'District31', 'State31', 'https://company_031.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC31', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00032', 'PAN00032', 'CMP032', 'DPSU32', N'Company_032', 'contact@company_032.com', '1234567890', 'info@company_032.com', 'Address 32', 'City32', '1000032', 1, 'District32', 'State32', 'https://company_032.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC32', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00033', 'PAN00033', 'CMP033', 'DPSU33', N'Company_033', 'contact@company_033.com', '1234567890', 'info@company_033.com', 'Address 33', 'City33', '1000033', 2, 'District33', 'State33', 'https://company_033.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC33', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00034', 'PAN00034', 'CMP034', 'DPSU34', N'Company_034', 'contact@company_034.com', '1234567890', 'info@company_034.com', 'Address 34', 'City34', '1000034', 3, 'District34', 'State34', 'https://company_034.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC34', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00035', 'PAN00035', 'CMP035', 'DPSU35', N'Company_035', 'contact@company_035.com', '1234567890', 'info@company_035.com', 'Address 35', 'City35', '1000035', 4, 'District35', 'State35', 'https://company_035.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC35', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00036', 'PAN00036', 'CMP036', 'DPSU36', N'Company_036', 'contact@company_036.com', '1234567890', 'info@company_036.com', 'Address 36', 'City36', '1000036', 1, 'District36', 'State36', 'https://company_036.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC36', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00037', 'PAN00037', 'CMP037', 'DPSU37', N'Company_037', 'contact@company_037.com', '1234567890', 'info@company_037.com', 'Address 37', 'City37', '1000037', 2, 'District37', 'State37', 'https://company_037.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC37', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00038', 'PAN00038', 'CMP038', 'DPSU38', N'Company_038', 'contact@company_038.com', '1234567890', 'info@company_038.com', 'Address 38', 'City38', '1000038', 3, 'District38', 'State38', 'https://company_038.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC38', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00039', 'PAN00039', 'CMP039', 'DPSU39', N'Company_039', 'contact@company_039.com', '1234567890', 'info@company_039.com', 'Address 39', 'City39', '1000039', 4, 'District39', 'State39', 'https://company_039.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC39', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00040', 'PAN00040', 'CMP040', 'DPSU40', N'Company_040', 'contact@company_040.com', '1234567890', 'info@company_040.com', 'Address 40', 'City40', '1000040', 1, 'District40', 'State40', 'https://company_040.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC40', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00041', 'PAN00041', 'CMP041', 'DPSU41', N'Company_041', 'contact@company_041.com', '1234567890', 'info@company_041.com', 'Address 41', 'City41', '1000041', 2, 'District41', 'State41', 'https://company_041.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC41', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00042', 'PAN00042', 'CMP042', 'DPSU42', N'Company_042', 'contact@company_042.com', '1234567890', 'info@company_042.com', 'Address 42', 'City42', '1000042', 3, 'District42', 'State42', 'https://company_042.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC42', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00043', 'PAN00043', 'CMP043', 'DPSU43', N'Company_043', 'contact@company_043.com', '1234567890', 'info@company_043.com', 'Address 43', 'City43', '1000043', 4, 'District43', 'State43', 'https://company_043.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC43', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00044', 'PAN00044', 'CMP044', 'DPSU44', N'Company_044', 'contact@company_044.com', '1234567890', 'info@company_044.com', 'Address 44', 'City44', '1000044', 1, 'District44', 'State44', 'https://company_044.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC44', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00045', 'PAN00045', 'CMP045', 'DPSU45', N'Company_045', 'contact@company_045.com', '1234567890', 'info@company_045.com', 'Address 45', 'City45', '1000045', 2, 'District45', 'State45', 'https://company_045.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC45', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00046', 'PAN00046', 'CMP046', 'DPSU46', N'Company_046', 'contact@company_046.com', '1234567890', 'info@company_046.com', 'Address 46', 'City46', '1000046', 3, 'District46', 'State46', 'https://company_046.com', NULL, 2, 2, 2, 2, 2, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC46', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00047', 'PAN00047', 'CMP047', 'DPSU47', N'Company_047', 'contact@company_047.com', '1234567890', 'info@company_047.com', 'Address 47', 'City47', '1000047', 4, 'District47', 'State47', 'https://company_047.com', NULL, 3, 3, 3, 3, 3, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC47', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00048', 'PAN00048', 'CMP048', 'DPSU48', N'Company_048', 'contact@company_048.com', '1234567890', 'info@company_048.com', 'Address 48', 'City48', '1000048', 1, 'District48', 'State48', 'https://company_048.com', NULL, 4, 4, 4, 4, 4, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC48', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00049', 'PAN00049', 'CMP049', 'DPSU49', N'Company_049', 'contact@company_049.com', '1234567890', 'info@company_049.com', 'Address 49', 'City49', '1000049', 2, 'District49', 'State49', 'https://company_049.com', NULL, 5, 5, 5, 5, 5, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC49', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

INSERT INTO CompanyMaster (CINNumber, Pan, CompanyRefNo, DPSU_Fk_Id, CompanyName, POC_Email, Phone, EmailId, Address, CityName, PinCode, Country_Fk_id, District, State, Website, Logo, CompanyScale_Fk_Id, CompanyType_Fk_Id, IndustryDomain_Fk_Id, IndustrySubDomain_Fk_Id, CompanyCoreExpertise_Fk_Id, CompanyRegistrationDate, CompanyStatus, CompanyCategory, CompanySubCategory, CompanyClass, ListingStatus, CompanyROC, CompanyIndustrialClassification, OtherScale, OtherCompanyType, OtherCompanyCoreExpertise, OtherCompIndDomain, OtherCompIndSubDomain, Final_Submit, IsActive, CreatedDate, CreatedBy, IPAddress) VALUES
('CIN00050', 'PAN00050', 'CMP050', 'DPSU50', N'Company_050', 'contact@company_050.com', '1234567890', 'info@company_050.com', 'Address 50', 'City50', '1000050', 3, 'District50', 'State50', 'https://company_050.com', NULL, 1, 1, 1, 1, 1, '2023-01-01', 'Active', 'CategoryA', 'SubCatA', 'ClassA', 'Listed', 'ROC', 'IC50', NULL, NULL, NULL, NULL, NULL, 1, 1, GETDATE(), 1, '127.0.0.1');

